name: Update README ⭐

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme-stars:
    name: Update Advent of Code starts to README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # You may pin to the exact commit or the version.
      # uses: k2bd/advent-readme-stars@7836395f6bdc8d97d1ccf73e88b218b7a0fcf9f5
      - uses: k2bd/advent-readme-stars@v1.0.1
        with:
          # AoC user ID. See the README for instructions on getting this.
          userId: 194566
          # AoC session cookie - make sure to keep this in a repo secret! See the README for instructions on getting this.
          sessionCookie: ${{ secrets.AOC_SESSION }}
          # AoC leaderboard ID. See the README for instructions on getting this.
          leaderboardId: 425502 # optional 
          # Unique text marking where the stars board section should go. Should be a comment, i.e. <!--- text enclosed in these markers --->, which is not used elsewhere in the README, and which should appear alone on its own line.
          # tableMarker: # optional, default is <!--- advent_readme_stars table --->
          # Symbol to use in the stars table
          # starSymbol: # optional, default is ⭐
          # Year to post the table for. Defaults to the year of the most recent December
          # year: # optional, default is 
          # Prefix to use for the header before the table, e.g. "##"
          # headerPrefix: # optional, default is ##
          # Location of the README file
          # readmeLocation: # optional, default is README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars

